apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: e-commerce/product
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: node-env
            - name: DB_TYPE
              valueFrom:
                configMapKeyRef:
                  name: product-config
                  key: db-type
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: product-config
                  key: db-host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: product-config
                  key: db-port
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: product-config
                  key: db-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: product-secret
                  key: db-password
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: product-config
                  key: db-name
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: common-secret
                  key: jwt-key
            - name: JWT_TTL
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: jwt-ttl
            - name: KAFKA_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: product-config
                  key: kafka-client-id
            - name: KAFKA_BROKER
              valueFrom:
                configMapKeyRef:
                  name: product-config
                  key: kafka-broker
---
apiVersion: v1
kind: Service
metadata:
  name: product-srv
spec:
  selector:
    app: product
  ports:
    - name: product
      protocol: TCP
      port: 3000
      targetPort: 3000
