apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-postgres-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-postgres
  template:
    metadata:
      labels:
        app: product-postgres
    spec:
      containers:
        - name: product-postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: product-postgres-data
              mountPath: /data/product/db
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: product-config
                  key: db-name
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: product-config
                  key: db-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: product-secret
                  key: db-password
      volumes:
        - name: product-postgres-data
          persistentVolumeClaim:
            claimName: product-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: product-postgres-srv
spec:
  selector:
    app: product-postgres
  ports:
    - name: product-db
      protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: product-postgres-node-port-srv
  labels:
    app: product-postgres
spec:
  type: NodePort
  selector:
    app: product-postgres
  ports:
    - name: product-node-port-db
      protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30002
