apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-redis-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-redis
  template:
    metadata:
      labels:
        app: cart-redis
    spec:
      containers:
        - name: cart-redis
          image: redis:7
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: cart-redis-data
              mountPath: /data
      volumes:
        - name: cart-redis-data
          persistentVolumeClaim:
            claimName: cart-redis-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: cart-redis-srv
spec:
  selector:
    app: cart-redis
  ports:
    - name: cart-db
      protocol: TCP
      port: 6379
      targetPort: 6379
