resources:
  - ./k8s/common/common-config.yaml
  - ./k8s/common/common-secret.yaml
  - ./k8s/ingress-srv.yaml
  - ./k8s/pgadmin-depl.yaml
  - ./k8s/user/user-config.yaml
  - ./k8s/user/user-depl.yaml
  - ./k8s/user/user-postgres-depl.yaml
  - ./k8s/user/user-postgres-pv.yaml
  - ./k8s/user/user-secret.yaml
  - ./k8s/product/product-config.yaml
  - ./k8s/product/product-depl.yaml
  - ./k8s/product/product-postgres-depl.yaml
  - ./k8s/product/product-postgres-pv.yaml
  - ./k8s/product/product-secret.yaml
  - ./k8s/kafka/kafka-depl.yaml
  - ./k8s/kafka/zookeper-depl.yaml
  - ./k8s/cart/cart-config.yaml
  - ./k8s/cart/cart-depl.yaml
  - ./k8s/cart/cart-redis-depl.yaml
  - ./k8s/cart/cart-redis-pvc.yaml
  - ./k8s/order/order-config.yaml
  - ./k8s/order/order-depl.yaml
  - ./k8s/order/order-postgres-depl.yaml
  - ./k8s/order/order-postgres-pv.yaml
  - ./k8s/order/order-secret.yaml
  - ./k8s/expiration/expiration-config.yaml
  - ./k8s/expiration/expiration-depl.yaml
  - ./k8s/expiration/expiration-redis-depl.yaml
