apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-postgres-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-postgres
  template:
    metadata:
      labels:
        app: user-postgres
    spec:
      containers:
        - name: user-postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: user-postgres-data
              mountPath: /data/user/db
          env:
            - name: POSTGRES_DB
              value: user
            - name: POSTGRES_USER
              value: root
            - name: POSTGRES_PASSWORD
              value: "1234"
      volumes:
        - name: user-postgres-data
          persistentVolumeClaim:
            claimName: user-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: user-postgres-srv
spec:
  selector:
    app: user-postgres
  ports:
    - name: user-db
      protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: ser-postgres-node-port-srv
  labels:
    app: user-postgres
spec:
  type: NodePort
  selector:
    app: user-postgres
  ports:
    - name: user-node-port-db
      protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30001
