apiVersion: v1
kind: PersistentVolume
metadata:
  name: order-postgres-pv
spec:
  capacity:
    storage: 1000Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /data/order-postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: order-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Mi
  storageClassName: standard