apiVersion: v1
kind: PersistentVolume
metadata:
  name: payment-postgres-pv
spec:
  capacity:
    storage: 1000Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /data/payment-postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: payment-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Mi
  storageClassName: standard