apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-postgres-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-postgres
  template:
    metadata:
      labels:
        app: payment-postgres
    spec:
      containers:
        - name: payment-postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: payment-postgres-data
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: payment-config
                  key: db-name
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: payment-config
                  key: db-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: payment-secret
                  key: db-password
      volumes:
        - name: payment-postgres-data
          persistentVolumeClaim:
            claimName: payment-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: payment-postgres-srv
spec:
  selector:
    app: payment-postgres
  ports:
    - name: payment-db
      protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: payment-postgres-node-port-srv
  labels:
    app: payment-postgres
spec:
  type: NodePort
  selector:
    app: payment-postgres
  ports:
    - name: payment-node-port-db
      protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30005
